In [4]:
## How to convert a float (32 bits) array into an integer (32 bits) in place
import numpy as np
a = np.arange(5, dtype=np.int32)
a = a.astype(np.float32, copy=False)
print(a)

[0. 1. 2. 3. 4.]


In [10]:
##Create a 3x3 matrix with values ranging from 0 to 8
a =  np.arange(0, 9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [12]:
##Find indices of non-zero elements from [1,2,0,0,4,0]
z = np.nonzero([1,2,0,0,4,0])
print(z)

(array([0, 1, 4], dtype=int64),)


In [14]:
##Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
y = np.diag(1+np.arange(4), k = -1)
print (y)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [16]:
##Create a 10x10x10 array with random values
mat = np.random.randint(10,size=(10,10,10))
print(mat)

[[[9 3 2 3 5 5 6 5 8 2]
  [7 3 6 1 5 6 4 4 9 2]
  [8 4 6 3 9 9 8 5 8 3]
  [2 5 7 8 8 8 9 1 0 6]
  [5 7 9 5 7 0 5 7 9 5]
  [8 4 3 0 4 3 5 8 4 6]
  [6 6 5 6 7 5 7 7 7 2]
  [7 4 5 1 2 9 2 2 3 8]
  [0 7 2 7 1 0 6 3 8 9]
  [1 1 1 8 8 4 7 4 6 8]]

 [[7 7 6 4 2 4 1 1 3 4]
  [3 2 1 8 6 0 4 2 2 9]
  [2 7 5 2 7 9 6 2 3 4]
  [1 2 7 3 9 6 8 9 4 5]
  [4 9 4 7 8 8 9 2 6 2]
  [2 1 6 4 9 1 1 1 3 5]
  [0 7 6 2 6 1 7 0 9 8]
  [2 6 1 9 5 2 1 8 7 7]
  [2 9 5 2 0 4 8 0 3 3]
  [2 3 3 1 8 5 3 3 5 1]]

 [[9 7 6 5 7 1 9 9 8 1]
  [8 4 6 1 3 4 2 8 7 3]
  [3 1 4 4 0 8 3 2 7 0]
  [6 3 6 0 2 1 0 6 4 7]
  [1 5 5 9 9 4 2 8 3 8]
  [3 8 1 4 3 1 7 3 8 6]
  [8 8 3 9 0 3 9 3 8 4]
  [9 5 0 0 6 7 6 5 7 0]
  [3 4 4 4 6 9 0 8 6 8]
  [6 5 8 6 7 0 1 6 8 4]]

 [[5 4 4 5 5 1 0 9 0 0]
  [6 1 4 0 5 7 3 3 4 0]
  [1 2 3 7 1 4 6 8 0 6]
  [3 4 5 2 3 7 7 3 2 1]
  [8 4 8 7 5 2 5 6 1 0]
  [3 3 1 1 0 9 7 5 6 0]
  [4 5 3 6 1 9 3 1 1 8]
  [6 4 2 1 2 8 1 4 0 4]
  [6 8 2 0 9 2 0 6 6 2]
  [3 5 0 5 7 8 9 0 9 8]]

 [[3 4 4 4 1 4 8 1 3 3]
  [7 3 7

In [18]:
##Create a 8x8 matrix and fill it with a checkerboard pattern
y = np.zeros ((8,8), dtype=int)
y[1::2, ::2]= 1
y[::2, 1::2] = 1
print (y)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [20]:
##Create a 10x10 array with random values and find the minimum and maximum values
x = np.random.random((10,10))
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[[0.97277578 0.80273817 0.66320549 0.08046406 0.3541216  0.67244332
  0.72298276 0.0530908  0.17539468 0.17633129]
 [0.89692848 0.73046404 0.52709223 0.2793343  0.02230976 0.82955426
  0.34766622 0.81424235 0.11143157 0.55136274]
 [0.642757   0.54505364 0.80942367 0.6543159  0.00998095 0.399678
  0.51101323 0.81631258 0.94279814 0.28096399]
 [0.60505646 0.75946208 0.83859483 0.60431209 0.82548235 0.69865473
  0.36934181 0.04690432 0.04787018 0.94834153]
 [0.05201115 0.26425743 0.69153243 0.03826217 0.17085789 0.74225247
  0.77163244 0.97272731 0.15416018 0.18149158]
 [0.71326933 0.61873176 0.7250487  0.66835109 0.42775707 0.7695481
  0.45887673 0.08498214 0.68336212 0.81407793]
 [0.41067419 0.02317225 0.05069159 0.89358398 0.35574149 0.02643054
  0.87951924 0.93397583 0.35356805 0.84757899]
 [0.49310677 0.18764422 0.81202505 0.17589634 0.31968298 0.3602755
  0.30309698 0.49141308 0.69017987 0.44721399]
 [0.53181833 0.86914837 0.34397582 0.18516938 0.91684478 0.10374759
  0.0291043  0.6

In [22]:
## Create a 10x10 matrix with row values ranging from 0 to 9
a = np.zeros((10,10))
a += np.arange(10)
print(a)

[[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]]


In [24]:
##Consider two random matrices A anb B, check if they are equal.
A = np.random.randint(0,1,4)
B = np.random.randint(0,1,4)

equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)

True
True


In [26]:
##Create a random vector of size 1000 and find the mean value
r = np.random.random(1000)
m = r.mean()
print (m)

0.49082238000085


In [28]:
##Create random vector of size 100 and replace the maximum value by 0
x = np.random.random(1000)
print(x)
x[x.argmax()] = 0
print("Maximum value replaced by 0:")
print(x)

[0.59079456 0.05822166 0.4319919  0.64444364 0.71135782 0.69389026
 0.98376804 0.32605593 0.38854997 0.19442506 0.24255539 0.3728866
 0.72748417 0.91705289 0.20944324 0.34888882 0.28376388 0.19427255
 0.98392338 0.25440611 0.60761625 0.92437142 0.53019118 0.4080458
 0.60434452 0.46710293 0.96472654 0.18994535 0.28131754 0.72022433
 0.79773454 0.94165903 0.42801973 0.07573652 0.35301956 0.39300887
 0.3626091  0.57800698 0.03580846 0.38936731 0.06901792 0.97758372
 0.72584796 0.54901186 0.50298165 0.80676862 0.68462905 0.33607754
 0.61765025 0.11706698 0.51349919 0.49308048 0.73387826 0.32279579
 0.038913   0.91993465 0.77947337 0.36315601 0.72265711 0.19192367
 0.21117616 0.94482162 0.81188019 0.56612666 0.36732829 0.26434141
 0.74177873 0.85331752 0.54190932 0.13967718 0.86715361 0.74006754
 0.78768208 0.50559549 0.0649034  0.91968232 0.00261742 0.13551017
 0.14555844 0.09246822 0.5126268  0.91999104 0.78135124 0.52365405
 0.92107045 0.78687138 0.99364461 0.70379662 0.1938629  0.008633

In [31]:
##Create a 5X2 integer array from a range between 100 to 200 such that the difference between each element is 10
sampleArray = np.arange(100, 200, 10)
sampleArray = sampleArray.reshape(5,2)
print (sampleArray)

[[100 110]
 [120 130]
 [140 150]
 [160 170]
 [180 190]]


In [33]:
##Following is the provided numPy array. Return array of items by taking the third column from all rows
#sampleArray = numpy.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]])
sampleArray = np.array([[11 ,22, 33], [44, 55, 66], [77, 88, 99]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of items in the third column from all rows")
newArray = sampleArray[...,2]
print(newArray)

Printing Input Array
[[11 22 33]
 [44 55 66]
 [77 88 99]]

 Printing array of items in the third column from all rows
[33 66 99]


In [35]:
##Return array of odd rows and even columns from below numpy array
#sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], [27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])
sampleArray = np.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]]) 
print("Printing Input Array")
print(sampleArray)

print("\n Printing array of odd rows and even columns")
new_Array = sampleArray[::2, 1::2]
print(new_Array)

Printing Input Array
[[ 3  6  9 12]
 [15 18 21 24]
 [27 30 33 36]
 [39 42 45 48]
 [51 54 57 60]]

 Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


In [36]:
#Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
##arrayOne = numpy.array([[5, 6, 9], [21 ,18, 27]])
###arrayTwo = numpy.array([[15 ,33, 24], [4 ,7, 1]])
arrayOne = np.array([[5, 6, 9], [21 ,18, 27]])
arrayTwo = np.array([[15 ,33, 24], [4 ,7, 1]])

resultArray  = arrayOne + arrayTwo
print("addition of two arrays is \n")
print(resultArray)

for num in np.nditer(resultArray, op_flags = ['readwrite']):
   num[...] = num*num
print("\nResult array after calculating the square root of all elements\n")
print(resultArray)

addition of two arrays is 

[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]


In [38]:
##Split the array into four equal-sized sub-arrays
##Note: Create an 8X3 integer array from a range between 10 to 34 such that the difference between each element is 1 and then Split the array into four equal-sized sub-arrays.
Array = np.arange(10, 34, 1)
Array = Array.reshape(8,3)
print (Array)

print("\nDividing 8X3 array into 4 sub array\n")
subArrays = np.split(Array, 4) 
print(subArrays)

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]

Dividing 8X3 array into 4 sub array

[array([[10, 11, 12],
       [13, 14, 15]]), array([[16, 17, 18],
       [19, 20, 21]]), array([[22, 23, 24],
       [25, 26, 27]]), array([[28, 29, 30],
       [31, 32, 33]])]


In [40]:
#Sort following NumPy array
##Case 1: Sort array by the second row
###Case 2: Sort the array by the second column
####sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

sort_Array_ByRow = sampleArray[:,sampleArray[1,:].argsort()]
print("Sorting Original array by secoond row")
print(sort_Array_ByRow)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Sorting Original array by secoond row
[[73 43 34]
 [12 22 82]
 [66 94 53]]


In [42]:
#Print max from axis 0 and min from axis 1 from the following 2-D array.
##sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

min_OfAxisOne = np.amin(sampleArray, 1) 
print("Printing min Of Axis 1")
print(min_OfAxisOne)

max_OfAxisOne = np.amax(sampleArray, 0) 
print("Printing max Of Axis 0")
print(max_OfAxisOne)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Printing min Of Axis 1
[34 12 53]
Printing max Of Axis 0
[82 94 73]


In [44]:
#Delete the second column from a given array and insert the following new column in its place.
##sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]])
###newColumn = numpy.array([[10,10,10]])
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


In [ ]:
##Create two 2-D arrays and Plot them using matplotlib